POST http://localhost:8080/omega/a
Content-Type: application/json

{
  "name" : "Maks",
  "id" : 7,
  "tool" : {"first" : "IDE","second" :  "lang"},
  "carList" : [{"value": "A"},{"value" : "VVVV"}]
}