POST http://localhost:8080/daddy/a
Content-Type: application/json

{
  "name" : "Diana",
  "id" : 4,
  "tool" : {"first" : "IDE","second" :  "lang"},
  "carlist" : [{"value": "A"},{"value" : "VVVV"}]
}