PUT http://localhost:8080/daddy/u?id=1
Content-Type: application/json

{
  "name" : "Demon",
  "id" : 77,
  "tool" : {"first" : "IDE","second" :  "Java lang"},
  "carlist" : [{"value": "L"},{"value" : "VVVV"}]
}